---

- name: Logrotate | main.yml | apt | Install Logrotate
  ansible.builtin.apt:
    name: logrotate
    state: latest
    update_cache: true
    cache_valid_time: 86400
  when: ansible_pkg_mgr == 'apt'

- name: Logrotate | main.yml | dnf | Install Logrotate
  ansible.builtin.dnf:
    name: logrotate
    state: latest
  when: ansible_pkg_mgr == 'dnf'

- name: Logrotate | main.yml | Create Old Directories
  ansible.builtin.file:
    path: "/var/log/{{ item.extra_options.olddir | default([]) }}"
    state: directory
    owner: "{{ item.extra_options.user | default([]) }}"
    group: "{{ item.extra_options.group | default([]) }}"
    mode: "{{ item.extra_options.mode | default([]) }}"
  with_items:
    - "{{ logrotate_files }}"
  failed_when: false

- name: Logrotate | main.yml | Write Parent logrotate.d Files
  ansible.builtin.template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}/{{ item.name }}"
    mode: '0750'
  with_items:
    - "{{ parent_logrotate_files }}"
  when: parent_logrotate_files is defined
  notify: Run Logrotate

- name: Logrotate | main.yml | Write Logrotate.d Files
  ansible.builtin.template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}/{{ item.name }}"
    backup: true
    mode: '0750'
  with_items: "{{ logrotate_files }}"
  notify: Run Logrotate

- name: Logrotate | main.yml | Create Facts Directory
  ansible.builtin.file:
    path: "/etc/ansible/facts.d"
    mode: '0775'
    state: directory

- name: Logrotate | main.yml | Register Configured Logrotate Files
  ansible.builtin.template:
    src: "logrotate.fact.j2"
    dest: "/etc/ansible/facts.d/logrotate.fact"
    mode: '0644'
  register: logrotate_write_facts

- name: Logrotate | main.yml | Reload Ansible Facts
  ansible.builtin.setup: # noqa: no-handler
    filter: "ansible_local"
  when: logrotate_write_facts.changed

- name: Logrotate | main.yml | List Configured Logrotate Files
  ansible.builtin.command: ls -1 {{ logrotate_conf_dir }}
  register: logrotate_files_present
  changed_when: false

- name: Logrotate | main.yml | Create Logrotate Backup Dir
  ansible.builtin.file:
    path: "{{ logrotate_backup_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0775'

- name: Logrotate | main.yml | Move old/existing Files
  ansible.builtin.copy:
    remote_src: true
    src: "{{ logrotate_conf_dir }}/{{ item }}"
    dest: "{{ logrotate_backup_dir }}/{{ item }}.old"
    mode: '0750'
  with_items: "{{ logrotate_files_present.stdout_lines }}"
  when: item|basename not in ansible_local.logrotate.logrotate_configured_files

- name: Logrotate | main.yml | Remove Unused Logrotate Files
  ansible.builtin.file:
    path: "{{ logrotate_conf_dir }}/{{ item }}"
    state: absent
  with_items: "{{ logrotate_files_present.stdout_lines }}"
  when: item|basename not in ansible_local.logrotate.logrotate_configured_files
